#!/usr/bin/env python3
"""
Raga Focus — Daily Video Idea Pipeline

Pulls fresh signals → scores candidates → writes proposal markdown.

Usage:
    cd pipeline
    python3 generate_ideas.py

Output:
    videos/proposals/YYYY-MM-DD.md   (today's ranked candidates)
    videos/proposals/rescue.md       (always-fresh rescue candidate list)
"""

import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from config import RULES, COMPETITORS
from signals import (
    load_own_catalog, fetch_all_competitor_uploads, find_rescue_candidates,
    competitor_problem_uses,
)
from scoring import generate_candidates, build_variants, build_tags, build_title
from historical import analyze_own_catalog, analyze_competitor_titles, recommend_lead_template
from suno import build_production_spec
from config import PROBLEM_TO_RAGA_MOOD


def _candidate_cluster(candidate):
    """Return the audience cluster of a candidate (e.g., 'evening_serene')."""
    p = candidate["components"]["problem"]["kw"].lower()
    for key, cluster in PROBLEM_TO_RAGA_MOOD.items():
        if key in p:
            return cluster
    return "unclassified"


def _dominant_cluster_of(catalog, days=5):
    """Find the cluster covered most often in the last N days of own videos."""
    from datetime import date as _date
    counts = {}
    today = _date.today()
    for v in catalog[:10]:
        days_ago = (today - v["publish_date"]).days
        if days_ago > days:
            continue
        title_lower = v["title"].lower()
        for key, cluster in PROBLEM_TO_RAGA_MOOD.items():
            if key in title_lower:
                counts[cluster] = counts.get(cluster, 0) + 1
                break
    if not counts:
        return None, {}
    dominant = max(counts.items(), key=lambda x: x[1])[0]
    return dominant, counts


def split_candidates_by_cluster(candidates, catalog):
    """Return (double_down_pick, diversify_pick, others) — top per track."""
    dominant_cluster, cluster_counts = _dominant_cluster_of(catalog)
    in_dominant = []
    out_dominant = []
    for c in candidates:
        cluster = _candidate_cluster(c)
        c["_cluster"] = cluster
        if dominant_cluster and cluster == dominant_cluster:
            in_dominant.append(c)
        else:
            out_dominant.append(c)
    double_down = in_dominant[0] if in_dominant else None
    diversify   = out_dominant[0] if out_dominant else None
    others = [c for c in candidates if c is not double_down and c is not diversify][:3]
    return double_down, diversify, others, dominant_cluster, cluster_counts


ROOT = Path(__file__).resolve().parent.parent
PROPOSALS_DIR = ROOT / "videos/proposals"
PROPOSALS_DIR.mkdir(parents=True, exist_ok=True)


def render_proposal(date, candidates, competitor_data, rescues, own_hook_summary, comp_hook_summary, lead_recommendation):
    out = []
    out.append(f"# Video Idea Proposal — {date}")
    out.append("")
    out.append(f"_Generated by `pipeline/generate_ideas.py`. Fresh signals: own catalog + competitor RSS pulled at {datetime.now().strftime('%H:%M IST')}._")
    out.append("")

    # ── Hook recommendation ──
    out.append("## 🎯 Recommended hook template")
    rec_label, rec_rationale = lead_recommendation
    out.append(f"**Lead with: `{rec_label}`** — {rec_rationale}")
    out.append("")
    out.append("**Historical CTR by hook type — own catalog:**")
    out.append("| Hook | Videos | Avg CTR | Avg Impr | Avg Views |")
    out.append("|---|---|---|---|---|")
    for cls in ("seo", "question", "outcome", "mixed"):
        s = own_hook_summary.get(cls, {})
        if s.get("n"):
            out.append(f"| {cls} | {s['n']} | {s.get('avg_ctr', '—')}% | {s.get('avg_impr', '—')} | {s.get('avg_views', '—')} |")
    out.append("")
    out.append("**Competitor preference — last 30 days:**")
    out.append("| Hook | Videos |")
    out.append("|---|---|")
    for cls in ("seo", "question", "outcome", "mixed"):
        s = comp_hook_summary.get(cls, {})
        if s.get("n"):
            out.append(f"| {cls} | {s['n']} |")
    out.append("")

    # ── Top candidates ──
    out.append("## 🏆 Top Candidates (ranked)")
    out.append("")
    for i, c in enumerate(candidates, 1):
        comp = c["components"]
        # Strategy badge — competitor / niche / moonshot
        STRAT_ICONS = {"competitor": "🎯", "niche": "💎", "moonshot": "🌙"}
        STRAT_LABELS = {"competitor": "COMPETITOR-COUNTER", "niche": "NICHE DOUBLING-DOWN", "moonshot": "MOONSHOT"}
        s = c.get("strategy", "")
        s_badge = f"{STRAT_ICONS.get(s, '•')} {STRAT_LABELS.get(s, s.upper())}" if s else ""
        out.append(f"### #{i} — {s_badge} — Score {c['score']}")
        if c.get("strategy_note"):
            out.append(f"_{c['strategy_note']}_")
        out.append(f"**Title:** `{c['title']}`")
        out.append(f"**Length:** {len(c['title'])} chars")
        out.append("")
        out.append("**Reasons:**")
        for r in c["reasons"]:
            out.append(f"- {r}")
        out.append("")

        # A/B/C variants
        variants = build_variants(comp["problem"], comp["hz"], comp["instrument"], comp["raga"], comp["wave"])
        out.append("**A/B/C variants** (for YouTube title A/B test — pick A vs B based on hook recommendation above):")
        labels = {
            "A_seo":      "A — SEO-led (search ranking)",
            "B_question": "B — Question-led (cold-feed CTR)",
            "C_outcome":  "C — Outcome-led (warm cohort)",
        }
        for key, v in variants.items():
            out.append(f"- **{labels[key]}** ({len(v)} chars): `{v}`")
        out.append("")
        # Thumbnail text — 3 variants from thumbnail_text.py (each has alts as backup)
        from thumbnail_text import build_thumbnail_text_variants
        try:
            thumb_variants = build_thumbnail_text_variants(comp["problem"]["kw"])
            out.append("**🖼️ Thumbnail overlay text (3 variants — validate each in VidIQ):**")
            for tv in thumb_variants:
                alts = " · alts: " + " / ".join(f"`{a}`" for a in tv["alts"]) if tv.get("alts") else ""
                out.append(f"- **{tv['label']}** — `{tv['text']}` _(strategy: {tv['strategy']})_{alts}")
            out.append("")
        except Exception as _e:
            # Fallback if no bucket match
            out.append(f"_Thumbnail text overlay: `{comp['problem'].get('question', '')}` (fallback — no thumbnail bucket match)._")
            out.append("")

        # Tags — annotate each with VidIQ score from keyword_bank.csv (or "untested")
        tags = build_tags(comp["problem"], comp["instrument"], comp["hz"], comp["raga"], comp["wave"])
        tag_str = ", ".join(tags)
        out.append(f"**Tags ({len(tag_str)}/500 chars, {len(tags)} tags):**")
        out.append(f"```")
        out.append(tag_str)
        out.append(f"```")
        # Score annotation table — cross-ref each tag against keyword_bank.csv
        from keyword_bank import load_all
        bank_index = {r["phrase"].strip().lower(): r for r in load_all()}
        scored, untested = [], []
        for t in tags:
            key = t.strip().lower()
            row = bank_index.get(key)
            if row and row.get("vidiq_score") is not None:
                scored.append((t, row["vidiq_score"]))
            else:
                untested.append(t)
        if scored or untested:
            out.append("")
            out.append("_Tag scores from `keyword_bank.csv`:_")
            if scored:
                scored.sort(key=lambda x: -x[1])
                line = " · ".join(f"`{t}` ({s})" for t, s in scored[:10])
                out.append(f"- ✅ **scored ({len(scored)})**: {line}{' …' if len(scored) > 10 else ''}")
            if untested:
                line = " · ".join(f"`{t}`" for t in untested[:8])
                out.append(f"- ⚠️ **untested ({len(untested)})**: {line}{' …' if len(untested) > 8 else ''}")
        out.append("")

        # FULL paste-ready description (replaces the lone Chapters block).
        # Title leads, then visceral hook, body, what-you'll-hear, chapters,
        # how-to-use, best-for, subscribe CTA, no-ads, hashtags.
        from description_hook import build_full_description
        # Top-7 highest-scoring tags become hashtags (already prioritized in build_tags)
        full_desc = build_full_description(
            problem_kw=comp["problem"]["kw"],
            instrument_name=comp["instrument"]["name"],
            raga_name=comp["raga"]["name"],
            hz=comp["hz"]["hz"],
            wave_name=comp["wave"]["wave"],
            duration_minutes=60,
            top_tags=tags[:10],
            title=variants.get("A_seo") or build_title(comp["problem"], comp["hz"], comp["instrument"], comp["raga"], comp["wave"]),
        )
        out.append("**📄 Full description** (paste into YouTube description box):")
        out.append("```")
        out.append(full_desc)
        out.append("```")
        out.append(f"_Length: {len(full_desc)} chars_")
        out.append("")

        # Suno prompt + production spec (only for the #1 candidate to keep proposal focused)
        if i == 1:
            spec = build_production_spec(c)
            out.append("**🎵 Suno prompt:**")
            out.append("```")
            out.append(spec["suno_prompt"])
            out.append("```")
            out.append(f"_Length: {len(spec['suno_prompt'])} chars · comma-separated tag format · {comp['wave']['wave']} wave undercurrent embedded._")
            out.append("")
            out.append("**Suno strategy:** " + spec["suno_strategy"])
            out.append("")
            out.append("**Critical Suno tips:**")
            for tip in spec["suno_critical_tips"]:
                out.append(f"- {tip}")
            out.append("")
            out.append("**Production spec (post-Suno):**")
            out.append(f"- **Binaural:** L={spec['binaural']['left_hz']}Hz, R={spec['binaural']['right_hz']}Hz → {spec['binaural']['wave_hz']}Hz {comp['wave']['wave']} entrainment ({spec['binaural']['level_db']}dB)")
            out.append(f"  - `{spec['binaural']['command']}`")
            out.append(f"- **Drone:** {spec['drone']['instrument']} ({spec['drone']['level_db']}dB)")
            out.append(f"- **Mix levels:** Suno {spec['mix_levels_db']['suno_layer']}dB · Binaural {spec['mix_levels_db']['binaural_layer']}dB · Drone {spec['mix_levels_db']['drone_layer']}dB")
            out.append(f"- **Fades:** {spec['fades']['in_sec']}s in / {spec['fades']['out_sec']}s out")
            out.append(f"- **Master:** {spec['master_lufs']} LUFS")
            out.append(f"- **Output:** {spec['output']}")
            out.append("")
            out.append("**Final merge:**")
            out.append(f"```bash")
            out.append(spec["merge_pattern"])
            out.append("```")
            out.append("")

        # Pre-publish gates the user must run
        out.append("**🔍 Manual gates before ship:**")
        if comp["problem"].get("vidiq_score") is None:
            out.append(f"- [ ] Run VidIQ on `{comp['problem']['kw']}` — must be ≥60 HIGH")
        out.append(f"- [ ] Run VidIQ on full title — must be ≥50")
        out.append(f"- [ ] YouTube search `{comp['problem']['kw']}` — screenshot top 5; check if dominated by single creator")
        if comp["problem"].get("vidiq_score") is None or comp["instrument"].get("vidiq_score") is None:
            out.append(f"- [ ] Cold-listen first 90s of audio — no stings, no jarring shifts")
        out.append("")
        out.append("---")
        out.append("")

    # ── Competitor pulse ──
    out.append("## 📡 Competitor pulse (last 14 days)")
    out.append("")
    for comp_name, uploads in competitor_data.items():
        out.append(f"### {comp_name}")
        if uploads and "error" in uploads[0]:
            out.append(f"- ⚠️ RSS fetch error: {uploads[0]['error']}")
            continue
        recent_14 = [u for u in uploads if u.get("days_ago", 99) <= 14]
        if not recent_14:
            out.append("- _No uploads in last 14 days_")
        else:
            for u in recent_14[:8]:
                out.append(f"- {u['published']} ({u['days_ago']}d ago) — {u['title']}")
        out.append("")

    # ── Rescue candidates ──
    out.append("## ♻️ Rescue Queue (high AVD% + low CTR — repackage targets)")
    out.append("")
    if not rescues:
        out.append("_No videos meet rescue criteria right now._")
    else:
        out.append(f"| Title | AVD% | CTR | Impr | Why rescue |")
        out.append(f"|---|---|---|---|---|")
        for r in rescues:
            short_title = r["title"][:60] + ("…" if len(r["title"]) > 60 else "")
            out.append(f"| {short_title} | {r['avd_pct']:.1f}% | {r['ctr_pct']:.2f}% | {r['impressions']} | retention strong, packaging failed |")
    out.append("")

    # ── Daily routine ──
    out.append("## ✅ Today's action")
    out.append("")
    if candidates:
        top = candidates[0]
        out.append(f"1. **Validate #{1} candidate** in VidIQ: `{top['components']['problem']['kw']}` + full title")
        out.append(f"2. **Search YouTube** for `{top['components']['problem']['kw']}` — confirm top-5 isn't dominated")
        out.append(f"3. **If gates pass:** approve title, brief thumbnail, generate Suno audio")
        out.append(f"4. **If gates fail:** revise with #2 candidate")
    out.append("")

    return "\n".join(out)


def main():
    today = datetime.now().date().isoformat()
    print(f"[{today}] Loading own catalog from REACH_HISTORY.csv …")
    catalog = load_own_catalog()
    print(f"  → {len(catalog)} videos in catalog")

    print(f"[{today}] Fetching competitor RSS feeds …")
    competitor_data = fetch_all_competitor_uploads(days=30)
    for name, uploads in competitor_data.items():
        if uploads and "error" in uploads[0]:
            print(f"  ⚠️ {name}: RSS fetch failed ({uploads[0]['error']})")
        else:
            print(f"  ✓ {name}: {len(uploads)} uploads in last 30d")

    print(f"[{today}] Analyzing historical title performance …")
    own_hook_summary = analyze_own_catalog(catalog)
    comp_hook_summary = analyze_competitor_titles(competitor_data, days=30)
    lead_rec = recommend_lead_template(own_hook_summary, comp_hook_summary)
    print(f"  → Hook recommendation: {lead_rec[0]}  ({lead_rec[1]})")

    print(f"[{today}] Generating candidates …")
    candidates = generate_candidates(catalog, competitor_data, top_n=3)
    print(f"  → {len(candidates)} ranked candidates")

    print(f"[{today}] Finding rescue candidates …")
    rescues = find_rescue_candidates(
        catalog,
        min_avd=RULES["rescue_min_avd_pct"],
        max_ctr=RULES["rescue_max_ctr_pct"],
        max_impr=RULES["rescue_max_impressions"],
    )
    print(f"  → {len(rescues)} rescue candidates")

    print(f"[{today}] Mining competitor titles for new keyword opportunities …")
    try:
        from discover_problem_hooks import discover as discover_hooks
        keyword_opportunities = discover_hooks(top_n=10)
    except Exception as _e:
        print(f"  ⚠ discovery skipped: {_e}")
        keyword_opportunities = []
    print(f"  → {len(keyword_opportunities)} untested phrases mined from competitor RSS")

    # Build a structured Competitor Pulse summary (last 7 days, grouped by competitor)
    competitor_pulse = {}
    for comp_name, uploads in competitor_data.items():
        recent = [u for u in uploads if "error" not in u and u.get("days_ago", 999) <= 7]
        recent.sort(key=lambda u: u.get("days_ago", 999))
        competitor_pulse[comp_name] = [
            {
                "title":    u["title"],
                "days_ago": u.get("days_ago", 0),
                "video_id": u.get("video_id", ""),
                "views":    u.get("views"),
                "likes":    u.get("likes"),
                "duration": u.get("duration"),
            }
            for u in recent
        ]

    print(f"[{today}] Writing proposal …")
    body = render_proposal(today, candidates, competitor_data, rescues, own_hook_summary, comp_hook_summary, lead_rec)

    # Also write structured JSON sidecar for the bridge to consume
    import json as _json
    json_path = PROPOSALS_DIR / f"{today}.json"
    def _serialize(obj):
        if isinstance(obj, dict):
            return {k: _serialize(v) for k, v in obj.items()}
        if isinstance(obj, list):
            return [_serialize(x) for x in obj]
        if hasattr(obj, "__dict__"):
            return _serialize(obj.__dict__)
        return obj
    json_path.write_text(_json.dumps({
        "date": today,
        "candidates": _serialize(candidates),
        "lead_recommendation": list(lead_rec),
        "keyword_opportunities": _serialize(keyword_opportunities),
        "competitor_pulse": _serialize(competitor_pulse),
    }, indent=2, default=str))
    print(f"  ✓ {json_path}")
    out_path = PROPOSALS_DIR / f"{today}.md"
    out_path.write_text(body)
    print(f"  ✓ {out_path}")

    print()
    if candidates:
        print(f"━━━ TOP CANDIDATE ━━━")
        print(f"  {candidates[0]['title']}")
        print(f"  Score: {candidates[0]['score']}")


if __name__ == "__main__":
    main()
