"""
Playbook generators — compute the auto-derivable playbook data files.

Generates:
  - data/playbook/instrument_lane_fit.json  (from shipped_titles_v2_enriched.csv)
  - data/playbook/phrase_locks.json         (from shipped_titles.csv with 20-day window)
  - data/playbook/_generated_at.txt

Hand-authored files (NOT regenerated by this script):
  - playbook_rules.yaml
  - theme_performance.json
  - anti_patterns.json
  - thumbnail_format_rules.json

Run:
    python3 pipeline/playbook_generators.py
"""
import csv
import json
import re
from collections import defaultdict
from datetime import date, datetime, timedelta
from pathlib import Path
from statistics import mean, median

DASHBOARD_DIR = Path(__file__).parent.parent
DATA_DIR = DASHBOARD_DIR / "data"
PLAYBOOK_DIR = DATA_DIR / "playbook"
PLAYBOOK_DIR.mkdir(parents=True, exist_ok=True)

STOPWORDS = {
    "music","hour","hours","1","2","3","with","for","and","the","a","an","of","to","in","on","at",
    "your","my","this","that","new","raga","ragas","video","track","mix","ft","feat","hd","4k",
    "session","sessions","instrumental","minute","min","mins","minutes","is","are","be","you",
    "indian","classical",
}

DESCRIPTOR_WORDS = {
    "slow","deep","gentle","soft","calm","calming","soothing","peaceful","relaxing","relaxation",
    "healing","mindful","meditation","ambient",
}


def is_distinctive_bigram(w1: str, w2: str) -> bool:
    """A bigram is 'distinctive' if both words are >=3 chars, not stopwords, not pure descriptors."""
    if len(w1) < 3 or len(w2) < 3:
        return False
    if w1 in STOPWORDS or w2 in STOPWORDS:
        return False
    # Reject if BOTH are pure descriptors (slow + deep) — single descriptor + noun is fine
    if w1 in DESCRIPTOR_WORDS and w2 in DESCRIPTOR_WORDS:
        return False
    return True


def extract_distinctive_bigrams(text: str) -> list:
    """Return list of distinctive 2-word phrases from text."""
    words = re.findall(r"[A-Za-z']+", text.lower())
    return [
        f"{words[i]} {words[i+1]}"
        for i in range(len(words) - 1)
        if is_distinctive_bigram(words[i], words[i+1])
    ]


# ─────────────────────────────────────────────────────────
# Generator 1: phrase_locks.json
# ─────────────────────────────────────────────────────────
def generate_phrase_locks(lock_window_days: int = 20) -> dict:
    """
    Read shipped_titles.csv → emit per-distinctive-phrase lock entry with free-again date.
    """
    shipped_path = DATA_DIR / "shipped_titles.csv"
    if not shipped_path.exists():
        return {"version": 1, "lock_window_days": lock_window_days, "locks": []}

    today = date.today()
    cutoff = today - timedelta(days=lock_window_days)

    # bigram → list of (shipped_on_date, title)
    phrase_uses = defaultdict(list)
    with open(shipped_path) as f:
        for r in csv.DictReader(f):
            try:
                ship_date = datetime.strptime(r["shipped_on"], "%Y-%m-%d").date()
            except (ValueError, KeyError):
                continue
            if ship_date < cutoff:
                continue
            title = r.get("title", "")
            for bg in extract_distinctive_bigrams(title):
                phrase_uses[bg].append((ship_date, title))

    # Build locks: for each bigram, use the MOST RECENT ship date
    locks = []
    for phrase, uses in sorted(phrase_uses.items()):
        last_date, last_title = max(uses, key=lambda x: x[0])
        free_again = last_date + timedelta(days=lock_window_days)
        days_remaining = (free_again - today).days
        if days_remaining < 0:
            continue
        locks.append({
            "phrase": phrase,
            "last_used": last_date.isoformat(),
            "from_title": last_title,
            "free_again": free_again.isoformat(),
            "days_remaining": days_remaining,
        })

    locks.sort(key=lambda x: x["free_again"])
    return {
        "version": 1,
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "lock_window_days": lock_window_days,
        "locks": locks,
    }


# ─────────────────────────────────────────────────────────
# Generator 2: instrument_lane_fit.json
# ─────────────────────────────────────────────────────────
def classify_family(title: str) -> str:
    t = title.lower()
    if re.search(r"(reset|recovery|reboot)", t): return "reset"
    if re.search(r"(healing|comfort|emotional|grief|release)", t): return "healing"
    if re.search(r"(sleep|asleep|insomnia|bedtime|drift off|night)", t): return "sleep"
    if re.search(r"(anxiety|anxious|stress|burnout|panic|overthink|overwhelm)", t): return "anxiety_stress"
    if re.search(r"(calm|peaceful|soothing|relax|gentle|quiet|stillness|tranquil|breathe)", t): return "calm"
    if re.search(r"(focus|concentration|productive|deep work|study|memory|brain fog|clarity|sharp|adhd|cognitive)", t): return "focus"
    if re.search(r"(positive|joyful|happy|uplifting|feel good|bright|cheerful|energy|mood|yoga)", t): return "uplifting"
    if re.search(r"(nostalgia|missing|homesick|memory|memories)", t): return "nostalgia"
    return "other"


def get_instrument(title: str) -> str:
    t = title.lower()
    for inst in ["sitar","veena","sarangi","bansuri","surbahar","sarod","santoor","tanpura",
                 "dilruba","esraj","violin","cello","tabla","bamboo flute","acoustic guitar",
                 "oud","swaramandal"]:
        if inst in t:
            return inst.replace(" ", "_")
    return "none"


def generate_instrument_lane_fit() -> dict:
    """Compute CTR/AVD per (instrument, lane) cell from enriched CSV."""
    enriched_path = DATA_DIR / "shipped_titles_v2_enriched.csv"
    if not enriched_path.exists():
        return {"version": 1, "matrix": {}}

    cells = defaultdict(list)
    instrument_overall = defaultdict(list)
    lane_overall = defaultdict(list)

    with open(enriched_path) as f:
        for r in csv.DictReader(f):
            if r.get("short_form", "").strip().lower() == "true":
                continue
            try:
                ctr = float(r["ctr_pct"]) if r.get("ctr_pct") else None
                avd = float(r["avd_pct"]) if r.get("avd_pct") else None
                views = int(r["views"]) if r.get("views") else 0
            except (ValueError, KeyError):
                continue
            if ctr is None or avd is None:
                continue
            inst = r.get("instrument", "").strip().lower() or "none"
            inst = inst.replace(" ", "_")
            family = r.get("family", "other")
            if family == "other":
                # re-classify if family column is generic
                family = classify_family(r.get("title", ""))
            key = (inst, family)
            cells[key].append({"ctr": ctr, "avd": avd, "views": views, "title": r.get("title","")})
            instrument_overall[inst].append({"ctr": ctr, "avd": avd, "views": views})
            lane_overall[family].append({"ctr": ctr, "avd": avd, "views": views})

    # Build matrix
    matrix = {}
    for (inst, lane), items in cells.items():
        ctrs = [i["ctr"] for i in items]
        avds = [i["avd"] for i in items]
        viewss = [i["views"] for i in items]
        top_title = max(items, key=lambda x: x["avd"])["title"]
        matrix[f"{inst}__{lane}"] = {
            "instrument": inst,
            "lane": lane,
            "n": len(items),
            "ctr_avg": round(mean(ctrs), 2),
            "avd_avg": round(mean(avds), 2),
            "views_med": int(median(viewss)),
            "views_max": max(viewss),
            "top_title": top_title[:80],
        }

    # Instrument overall
    instrument_summary = {}
    for inst, items in instrument_overall.items():
        ctrs = [i["ctr"] for i in items]
        avds = [i["avd"] for i in items]
        instrument_summary[inst] = {
            "n": len(items),
            "ctr_avg": round(mean(ctrs), 2),
            "avd_avg": round(mean(avds), 2),
            "role": classify_instrument_role(inst, mean(ctrs), mean(avds)),
        }

    # Lane overall
    lane_summary = {}
    for lane, items in lane_overall.items():
        ctrs = [i["ctr"] for i in items]
        avds = [i["avd"] for i in items]
        lane_summary[lane] = {
            "n": len(items),
            "ctr_avg": round(mean(ctrs), 2),
            "avd_avg": round(mean(avds), 2),
        }

    return {
        "version": 1,
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "channel_ctr_avg": 3.63,
        "channel_avd_avg": 21.3,
        "instrument_summary": instrument_summary,
        "lane_summary": lane_summary,
        "matrix": matrix,
    }


def classify_instrument_role(inst: str, ctr_avg: float, avd_avg: float) -> str:
    """Classify instrument role: REACH / RETENTION / CTR_HERO / WORKHORSE / MOONSHOT."""
    # Hand-tuned per playbook §5
    if inst == "sitar":
        return "REACH_HERO"  # algorithm-pushed
    if inst == "veena" and avd_avg >= 26:
        return "RETENTION_HERO"
    if inst == "bansuri" and ctr_avg >= 4.5:
        return "CTR_HERO"
    if inst in {"santoor", "surbahar", "sarangi"}:
        return "WORKHORSE"
    if inst in {"sarod", "esraj", "tanpura"}:
        return "MOONSHOT_UNTESTED_MODERN"
    if inst == "dilruba":
        return "MID_WORKHORSE"
    return "UNCLASSIFIED"


# ─────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────
def main():
    print("Generating phrase_locks.json...")
    locks = generate_phrase_locks(lock_window_days=20)
    locks_path = PLAYBOOK_DIR / "phrase_locks.json"
    locks_path.write_text(json.dumps(locks, indent=2))
    print(f"  ✓ {len(locks['locks'])} locked phrases → {locks_path.relative_to(DASHBOARD_DIR)}")

    print("Generating instrument_lane_fit.json...")
    fit = generate_instrument_lane_fit()
    fit_path = PLAYBOOK_DIR / "instrument_lane_fit.json"
    fit_path.write_text(json.dumps(fit, indent=2))
    print(f"  ✓ {len(fit['matrix'])} instrument×lane cells → {fit_path.relative_to(DASHBOARD_DIR)}")

    # Generated-at marker
    (PLAYBOOK_DIR / "_generated_at.txt").write_text(
        f"playbook_generators.py last run: {datetime.now().isoformat(timespec='seconds')}\n"
    )
    print(f"✓ All auto-generated files updated in {PLAYBOOK_DIR.relative_to(DASHBOARD_DIR)}")


if __name__ == "__main__":
    main()
